FROM python:3.11-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

RUN pip install streamlit \
    pandas \
    matplotlib\
    seaborn \
    dotenv

WORKDIR /app
COPY  ./streamlit-app /app/

CMD ["streamlit", "run", "app.py", "--server.runOnSave", "false"]
